### ISSUE TITLE
Обнови доступную пряталку

### ISSUE THREAD

**Issue by firefoxic** [htmlacademy-adaptive/661093-cat-energy-22#32]
> Д16. Нет глобальных стилей тегов.

https://github.com/htmlacademy-adaptive/661093-cat-energy-22/blob/b3083e56ecf6e32d01edea0c9905841dae6187ee/source/sass/global.scss#L23-L36

Этот странный и опастный снипет когда-то как-то просочился в Академию, но быстро одумались и выкинули его. А ты где-то раскопал его. Лучше избавиться от этого нагромождения в селекторе, оставив только класс.
А ещё лучше заменить набор свойств на более современный и понятный, да ещё и короткий вариант:
```css
.visually-hidden {
  postition: fixed;
  transform: scale(0);
}
```
